### ISSUE TITLE
Good work, I want to ask how  to split the train_data and test_data?

### ISSUE THREAD

**Issue by hellokevin96** [FanGhost/pytorchMF#1]

**Comment by moduxiaohunhun** [comment]
不需要loss.zero_grad()吗？

**Comment by FanGhost** [comment]
In this project, we use a random sampling strategy with uniform distribution, and there are other popular sampling strategy to split the train_data and test_data, such as leave-one-out [1].
[1].  https://arxiv.org/pdf/1905.11133v1.pdf
